### ISSUE TITLE
Provider - Error when credentials are wrong

### ISSUE THREAD

**Issue by gerardlemetayerc** [gerardlemetayerc/device42#6]
Need to implement try catch on connexion establishment.

**Current error :**
```
goroutine 28 [running]:
github.com/gerardlemetayerc/device42/device42.resourceDevice42DeviceCreate(0x0?, {0x1311360?, 0xc0003fe1e0})
        [userPath]/repos/terraform-provider-device42/device42/resource_virtual_machine.go:137 +0xf9c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1465a80?, {0x1465a80?, 0xc0001ff4d0?}, 0xd?, {0x1311360?, 0xc0003fe1e0?})
        [userPath]/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002ee1c0, {0x1465a80, 0xc0001ff4d0}, 0xc0004a0000, 0xc000498800, {0x1311360, 0xc0003fe1e0})
        [userPath]/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000384c18, {0x1465a80?, 0xc0001ff200?}, 0xc00007cfa0)
        [userPath]/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000000460, {0x1465a80?, 0xc00013ea20?}, 0xc00042e4d0)
        [userPath]/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x12ec5a0?, 0xc000000460}, {0x1465a80, 0xc00013ea20}, 0xc00042e460, 0x0)
        [userPath]/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00039e000, {0x14695a0, 0xc0000cb860}, 0xc000496900, 0xc000398b10, 0x1919700, 0x0)
        [userPath]/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00039e000, {0x14695a0, 0xc0000cb860}, 0xc000496900, 0x0)
        [userPath]/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        [userPath]/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        [userPath]/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-device42_v0.0.1_windows_amd64.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that
```

Notice : Device creation / deletion works.

**Comment by gerardlemetayerc** [comment]
Corrective done for devices.
